//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InternalDocument
    {
        public long intdocID { get; set; }
        public long docID { get; set; }
        public Nullable<byte> nmcID { get; set; }
        public Nullable<byte> nmcSubID { get; set; }
        public Nullable<byte> actionTypeID { get; set; }
        public string responseDocNo { get; set; }
        public Nullable<byte> conTypeID { get; set; }
    }
}
