//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocumentOperation
    {
        public long doID { get; set; }
        public long docID { get; set; }
        public int userID { get; set; }
        public Nullable<byte> conTypeID { get; set; }
        public Nullable<int> fromUserID { get; set; }
        public Nullable<System.DateTime> doDate { get; set; }
        public Nullable<byte> doStatus { get; set; }
        public Nullable<byte> doLock { get; set; }
    }
}
