//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocumentFiles
    {
        public long dfID { get; set; }
        public Nullable<long> docID { get; set; }
        public Nullable<byte> attFileTypeID { get; set; }
        public string dfTitle { get; set; }
        public string dfPageCount { get; set; }
        public string dfName { get; set; }
        public string dfContent { get; set; }
        public string dfGUID { get; set; }
        public byte dfStatus { get; set; }
    }
}
