//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int usrID { get; set; }
        public string usrName { get; set; }
        public string usrPassword { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
