//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int empID { get; set; }
        public Nullable<int> usrID { get; set; }
        public string empName { get; set; }
        public string empSurname { get; set; }
        public string empMiddleName { get; set; }
        public string empMail { get; set; }
        public string empPhone { get; set; }
    }
}
