//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IUMDBEntity : DbContext
    {
        public IUMDBEntity()
            : base("name=IUMDBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ActionType> tbl_ActionType { get; set; }
        public virtual DbSet<tbl_AttachFileType> tbl_AttachFileType { get; set; }
        public virtual DbSet<tbl_ContactType> tbl_ContactType { get; set; }
        public virtual DbSet<tbl_DocContentType> tbl_DocContentType { get; set; }
        public virtual DbSet<tbl_DocConTypeOperation> tbl_DocConTypeOperation { get; set; }
        public virtual DbSet<tbl_DocToOperation> tbl_DocToOperation { get; set; }
        public virtual DbSet<tbl_DocType> tbl_DocType { get; set; }
        public virtual DbSet<tbl_Document> tbl_Document { get; set; }
        public virtual DbSet<tbl_DocumentFiles> tbl_DocumentFiles { get; set; }
        public virtual DbSet<tbl_DocumentOperation> tbl_DocumentOperation { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_InternalDocument> tbl_InternalDocument { get; set; }
        public virtual DbSet<tbl_Nomenclature> tbl_Nomenclature { get; set; }
        public virtual DbSet<tbl_Position> tbl_Position { get; set; }
        public virtual DbSet<tbl_ServiceDocument> tbl_ServiceDocument { get; set; }
        public virtual DbSet<tbl_SubNomenclature> tbl_SubNomenclature { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
